spring.datasource.url=jdbc:postgresql://localhost:5432/taskdb
spring.datasource.username=postgres
spring.datasource.password=0000

spring.jpa.hibernate.ddl-auto=update

jwt.secret=my-dev-secret-key-my-dev-secret-key-123456789

management.endpoints.web.exposure.include=health,info